version: '3'
services:
  postgres:
    image: postgres:15
    container_name: ontop-postgres-container
    environment:
      POSTGRES_DB: ontopdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ontop-springboot-app-container
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL_DEV: jdbc:postgresql://postgres:5432/ontopdb
      DATABASE_USERNAME_DEV: myuser
      DATABASE_PASSWORD_DEV: mypassword
    depends_on:
      - postgres
