name: Build and deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    if: github.repository == 'yvan-lopez-it/ontop-challenge-bese-java'
    name: Setup, build, publish, and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and test with Maven
        run: mvn clean package

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag yvancho/ontop-challenge-be:1.0.0

      - name: Docker push
        run: ocker push yvancho/ontop-challenge-be:1.0.0

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set aws_region us-east-1

      - name: Push the new image ID in the Amazon ECS task definition
        id: task-def
        run: |
          IMAGE_ID=$(docker images -q ontop-challenge-be:1.0.0)
          echo "::set-output name=image::$IMAGE_ID"

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.image }}
          service: ontop-challenge-be-service
          cluster: ontop-challenge-bese-cluster
          wait-for-service-stability: true
