name: Build and deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    if: github.repository == 'yvan-lopez-it/ontop-challenge-bese-java'
    name: Setup, build, publish and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java 17
      - name: Set up jdk11
        uses: actions/checkout@v4
        with:
          java-version: 11
          server-id: github
          settings-path: ${{ github.workspace }}
      
      # Set up Maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.1

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn spring-boot:built-image
